### PR TITLE
Implement getGlobalState

### LINKED ISSUE #2: Expose global state for non-components
Similar to `setGlobalState`, could you add a `getGlobalState` ? For read-only access to state outside of components.

### PR DESCRIPTION
**Pull request by Slessi**
Resolves #2 

What do you think?

### CODE REVIEW

**Comment by dai-shi** [comment]
Thanks for your suggestion!
Before going into details, I'd like to ask your requirement.
How do you want to use this new feature?
Doesn't it need to be notified when a state is changed?

**Comment by Slessi** [comment]
This is for outside of a component.

I have an API client that wants to put a user JWT into request headers, and I store the token inside global state. So I need a function to read state as-is at the time of a request

**Comment by dai-shi** [comment]
@Slessi I got it. I will merge this PR and take it over. Unfortunately, `globalState` is not very good, though it may work more or less accidentally.

**Comment by dai-shi** [comment]
Released v2.1.0.

**Pull request merged**
