### PR TITLE
Fix getGlobalState

### PR DESCRIPTION
**Pull request by Slessi**
Need to update `stateItemValues ` before calling `this.setState` as a re-render can lead to calling `getGlobalState` before `stateItemValues` is updated

### CODE REVIEW

**Comment by dai-shi** [comment]
Hm, I didn’t notice that. Can you write test code for that?

**Comment by dai-shi** [comment]
@Slessi If writing it as a test is hard, can you provide a small example to reproduce a problem please?

**Comment by Slessi** [comment]
I had other problems and ended up writing my own version of this. Had tried writing a short piece of code which reproduces the problem but didn't manage.

**Comment by dai-shi** [comment]
That's unfortunate. Thanks anyway.

**Pull request closed without merging**
